"""Initial schema with all core models

Revision ID: 2284e7a9b8e5
Revises: 
Create Date: 2026-01-31 21:58:06.933696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '2284e7a9b8e5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offerer_role_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('role_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('weights', sa.JSON(), nullable=True),
    sa.Column('display_config', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offerer_role_configs_role_name'), 'offerer_role_configs', ['role_name'], unique=True)
    op.create_table('offerers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('company', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('role_filter', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offerers_email'), 'offerers', ['email'], unique=True)
    op.create_table('questionnaires',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seekers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('profile', sa.JSON(), nullable=True),
    sa.Column('questionnaire_progress', sa.JSON(), nullable=True),
    sa.Column('stats_card', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seekers_email'), 'seekers', ['email'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('role', sa.Enum('SEEKER', 'OFFERER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('questionnaire_id', sa.Uuid(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('question_type', sa.Enum('MULTIPLE_CHOICE', 'SCALE', 'TEXT', 'YES_NO', name='questiontype'), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('scoring_config', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['questionnaire_id'], ['questionnaires.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_questionnaire_id'), 'questions', ['questionnaire_id'], unique=False)
    op.create_table('seeker_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('headline', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('questionnaire_completed', sa.Boolean(), nullable=False),
    sa.Column('questionnaire_completed_at', sa.DateTime(), nullable=True),
    sa.Column('stats_card', sa.JSON(), nullable=True),
    sa.Column('stats_computed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seeker_profiles_user_id'), 'seeker_profiles', ['user_id'], unique=True)
    op.create_table('swipes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('offerer_id', sa.Uuid(), nullable=False),
    sa.Column('seeker_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.Enum('LIKE', 'DISLIKE', 'PASS', name='swipeaction'), nullable=False),
    sa.Column('swiped_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['offerer_id'], ['offerers.id'], ),
    sa.ForeignKeyConstraint(['seeker_id'], ['seekers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_swipes_offerer_id'), 'swipes', ['offerer_id'], unique=False)
    op.create_index(op.f('ix_swipes_seeker_id'), 'swipes', ['seeker_id'], unique=False)
    op.create_table('answers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('seeker_profile_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('answer_value', sa.JSON(), nullable=True),
    sa.Column('answered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['seeker_profile_id'], ['seeker_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answers_question_id'), 'answers', ['question_id'], unique=False)
    op.create_index(op.f('ix_answers_seeker_profile_id'), 'answers', ['seeker_profile_id'], unique=False)
    op.create_table('shortlists',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('offerer_id', sa.Uuid(), nullable=False),
    sa.Column('seeker_profile_id', sa.Uuid(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'CONTACTED', 'INTERVIEWING', 'REJECTED', 'HIRED', name='shortliststatus'), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['offerer_id'], ['offerers.id'], ),
    sa.ForeignKeyConstraint(['seeker_profile_id'], ['seeker_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shortlists_offerer_id'), 'shortlists', ['offerer_id'], unique=False)
    op.create_index(op.f('ix_shortlists_seeker_profile_id'), 'shortlists', ['seeker_profile_id'], unique=False)
    op.create_table('swipe_decisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('offerer_id', sa.Uuid(), nullable=False),
    sa.Column('seeker_profile_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.Enum('LIKE', 'DISLIKE', 'PASS', 'SUPER_LIKE', name='swipeaction'), nullable=False),
    sa.Column('role_config_id', sa.Uuid(), nullable=True),
    sa.Column('swiped_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['offerer_id'], ['offerers.id'], ),
    sa.ForeignKeyConstraint(['role_config_id'], ['offerer_role_configs.id'], ),
    sa.ForeignKeyConstraint(['seeker_profile_id'], ['seeker_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_swipe_decisions_offerer_id'), 'swipe_decisions', ['offerer_id'], unique=False)
    op.create_index(op.f('ix_swipe_decisions_seeker_profile_id'), 'swipe_decisions', ['seeker_profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_swipe_decisions_seeker_profile_id'), table_name='swipe_decisions')
    op.drop_index(op.f('ix_swipe_decisions_offerer_id'), table_name='swipe_decisions')
    op.drop_table('swipe_decisions')
    op.drop_index(op.f('ix_shortlists_seeker_profile_id'), table_name='shortlists')
    op.drop_index(op.f('ix_shortlists_offerer_id'), table_name='shortlists')
    op.drop_table('shortlists')
    op.drop_index(op.f('ix_answers_seeker_profile_id'), table_name='answers')
    op.drop_index(op.f('ix_answers_question_id'), table_name='answers')
    op.drop_table('answers')
    op.drop_index(op.f('ix_swipes_seeker_id'), table_name='swipes')
    op.drop_index(op.f('ix_swipes_offerer_id'), table_name='swipes')
    op.drop_table('swipes')
    op.drop_index(op.f('ix_seeker_profiles_user_id'), table_name='seeker_profiles')
    op.drop_table('seeker_profiles')
    op.drop_index(op.f('ix_questions_questionnaire_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_seekers_email'), table_name='seekers')
    op.drop_table('seekers')
    op.drop_table('questionnaires')
    op.drop_index(op.f('ix_offerers_email'), table_name='offerers')
    op.drop_table('offerers')
    op.drop_index(op.f('ix_offerer_role_configs_role_name'), table_name='offerer_role_configs')
    op.drop_table('offerer_role_configs')
    # ### end Alembic commands ###
