"""Initial migration: add all tables

Revision ID: 5ce988c23120
Revises: 
Create Date: 2026-01-31 21:45:56.866872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '5ce988c23120'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offerers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('company', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('role_filter', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offerers_email'), 'offerers', ['email'], unique=True)
    op.create_table('seekers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('profile', sa.JSON(), nullable=True),
    sa.Column('questionnaire_progress', sa.JSON(), nullable=True),
    sa.Column('stats_card', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seekers_email'), 'seekers', ['email'], unique=True)
    op.create_table('shortlists',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('offerer_id', sa.Uuid(), nullable=False),
    sa.Column('seeker_id', sa.Uuid(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['offerer_id'], ['offerers.id'], ),
    sa.ForeignKeyConstraint(['seeker_id'], ['seekers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shortlists_offerer_id'), 'shortlists', ['offerer_id'], unique=False)
    op.create_index(op.f('ix_shortlists_seeker_id'), 'shortlists', ['seeker_id'], unique=False)
    op.create_table('swipes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('offerer_id', sa.Uuid(), nullable=False),
    sa.Column('seeker_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.Enum('LIKE', 'DISLIKE', 'PASS', name='swipeaction'), nullable=False),
    sa.Column('swiped_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['offerer_id'], ['offerers.id'], ),
    sa.ForeignKeyConstraint(['seeker_id'], ['seekers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_swipes_offerer_id'), 'swipes', ['offerer_id'], unique=False)
    op.create_index(op.f('ix_swipes_seeker_id'), 'swipes', ['seeker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_swipes_seeker_id'), table_name='swipes')
    op.drop_index(op.f('ix_swipes_offerer_id'), table_name='swipes')
    op.drop_table('swipes')
    op.drop_index(op.f('ix_shortlists_seeker_id'), table_name='shortlists')
    op.drop_index(op.f('ix_shortlists_offerer_id'), table_name='shortlists')
    op.drop_table('shortlists')
    op.drop_index(op.f('ix_seekers_email'), table_name='seekers')
    op.drop_table('seekers')
    op.drop_index(op.f('ix_offerers_email'), table_name='offerers')
    op.drop_table('offerers')
    # ### end Alembic commands ###
